name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Create Changelog
        uses: Pingumania/actions-recent-changelog@main
        with:
          input: CHANGELOG.md
          output: RECENT_CHANGES.md

      - name: Create Retail Package
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_TOKEN }}
