name: Release

on:
  push:
    tags:
      - '**'

env:
  CF_API_KEY: ${{ secrets.CF_TOKEN }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Create Changelog
        uses: pngmn/actions-recent-changelog@main
        with:
          input: CHANGELOG.md
          output: RECENT_CHANGES.md

      - name: Create Retail Package
        uses: BigWigsMods/packager@master

      # - name: Create Classic Package
      #   uses: BigWigsMods/packager@master
      #   with:
      #     args: -g classic

      # - name: Create BCC Package
      #   uses: BigWigsMods/packager@master
      #   with:
      #     args: -g bcc
